name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Go ${{ matrix.go }} testing code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.13', '1.14']

    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: "Test code"
        run: go test -v .

#  build:
#    name: Test
#    runs-on: ubuntu-latest
#    steps:
#
#    - name: Set up Go 1.13
#      uses: actions/setup-go@v2
#      with:
#        go-version: 1.13
#      id: go
#
#    - name: Check out code into the Go module directory
#      uses: actions/checkout@v2
#
#    - name: Get dependencies
#      run: |
#        go get -v -t -d ./...
#        if [ -f Gopkg.toml ]; then
#            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#            dep ensure
#        fi
#
#    - name: Test
#      run: go test -v .
