name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Go ${{ matrix.go }} code testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.13', '1.14']
    steps:
      - name: Checkout go
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: "Code testing"
        run: go test -v .
